version: '3.0'

services:
  jenkins:
    restart: always
    container_name: jenkins
    image: xmartlabs/jenkins-android:latest
    privileged: true
    tty: true
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "./jenkins_home:/var/jenkins_home"
      - "/home/noman/Android/Sdk:/opt/android-sdk-linux"

# ref: https://github.com/jfrog/artifactory-docker-examples/blob/master/docker-compose/artifactory/artifactory-oss.yml
# ref: https://www.arvinep.com/2016/04/jenkins-docker-container-problem.html
  artifactory:
    restart: always
    container_name: artifactory
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    user: "${UID}:${GID}"
    privileged: true
    tty: true
    ports:
      - "8081:8081"
      - "8082:8082"
    volumes:
      - "./jforg_home/artifactory:/var/opt/jfrog/artifactory"
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
